---
name: Build
on:
  workflow_call:
    inputs:
      build_version:
        description: "The version to build.  It must be semver-compliant, and must not be for a tag that already exists."
        required: false
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: 0

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@f744c72a42b1995d7b0cbc314bde4bace7ac1fe1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          native-image-job-reports: 'true'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244

      - name: Determine Build Version
        env:
          ENGINE_BUILD_VERSION: ${{ inputs.build_version }}
        run: |
          ./gradlew writeVersion

      - name: Read Version File
        id: getversion
        run: |
          test -f build/version.txt
          echo "version=$(cat build/version.txt)" >> "$GITHUB_OUTPUT"

      - name: Build
        env:
          ENGINE_BUILD_VERSION: ${{ steps.getversion.outputs.version }}
        run: |
          ./gradlew build

      - name: Upload JVM Artifacts
        if: inputs.build_version != ''
        uses: actions/upload-artifact@v4
        with:
          name: dist-jvm-jars
          path: |
            build/libs/*.jar
            recorder/build/libs/*.jar
          if-no-files-found: error
